services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - 5672:5672
    - 15672:15672
  postgres:
    image: postgres:16.1
    environment:
    - POSTGRES_DB=gestao
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=P4ssword!
    ports:
    - 5433:5432
